# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 568)
        MainWindow.setMinimumSize(QtCore.QSize(430, 568))
        MainWindow.setMaximumSize(QtCore.QSize(430, 568))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 221, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 201, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 60, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 380, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 180, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(240, 200, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 410, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(240, 280, 91, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 300, 121, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 280, 61, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 200, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(240, 380, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(240, 410, 61, 16))
        self.label_17.setObjectName("label_17")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 0, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 411, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 220, 411, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 320, 411, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 470, 411, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.I_ip = QtWidgets.QLabel(self.centralwidget)
        self.I_ip.setGeometry(QtCore.QRect(70, 60, 121, 16))
        self.I_ip.setObjectName("I_ip")
        self.E_ip = QtWidgets.QLabel(self.centralwidget)
        self.E_ip.setGeometry(QtCore.QRect(300, 60, 141, 16))
        self.E_ip.setObjectName("E_ip")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(340, 280, 121, 16))
        self.status.setObjectName("status")
        self.processor = QtWidgets.QLabel(self.centralwidget)
        self.processor.setGeometry(QtCore.QRect(70, 180, 101, 16))
        self.processor.setObjectName("processor")
        self.OS = QtWidgets.QLabel(self.centralwidget)
        self.OS.setGeometry(QtCore.QRect(70, 200, 101, 16))
        self.OS.setObjectName("OS")
        self.OS_Type = QtWidgets.QLabel(self.centralwidget)
        self.OS_Type.setGeometry(QtCore.QRect(310, 200, 101, 16))
        self.OS_Type.setObjectName("OS_Type")
        self.Arch = QtWidgets.QLabel(self.centralwidget)
        self.Arch.setGeometry(QtCore.QRect(310, 180, 101, 16))
        self.Arch.setObjectName("Arch")
        self.Auth_stat = QtWidgets.QLabel(self.centralwidget)
        self.Auth_stat.setGeometry(QtCore.QRect(120, 300, 111, 16))
        self.Auth_stat.setObjectName("Auth_stat")
        self.Hostname = QtWidgets.QLabel(self.centralwidget)
        self.Hostname.setGeometry(QtCore.QRect(70, 280, 101, 16))
        self.Hostname.setObjectName("Hostname")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(70, 380, 111, 16))
        self.Username.setObjectName("Username")
        self.aid = QtWidgets.QLabel(self.centralwidget)
        self.aid.setGeometry(QtCore.QRect(70, 410, 111, 16))
        self.aid.setObjectName("aid")
        self.Auth_key = QtWidgets.QLabel(self.centralwidget)
        self.Auth_key.setGeometry(QtCore.QRect(300, 380, 111, 16))
        self.Auth_key.setObjectName("Auth_key")
        self.Auth_salt = QtWidgets.QLabel(self.centralwidget)
        self.Auth_salt.setGeometry(QtCore.QRect(300, 410, 111, 16))
        self.Auth_salt.setObjectName("Auth_salt")
        self.FetchIP = QtWidgets.QPushButton(self.centralwidget)
        self.FetchIP.setGeometry(QtCore.QRect(340, 90, 75, 23))
        self.FetchIP.setObjectName("FetchIP")
        self.Login = QtWidgets.QPushButton(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(330, 440, 75, 23))
        self.Login.setObjectName("Login")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(330, 540, 75, 23))
        self.Exit.setObjectName("Exit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 540, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 540, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client- CyberHawk"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">IP Address:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">System Details:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Connection Status:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Account Details: </span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Internal IP:"))
        self.label_6.setText(_translate("MainWindow", "External IP: "))
        self.label_7.setText(_translate("MainWindow", "Procesor:"))
        self.label_8.setText(_translate("MainWindow", "Username:"))
        self.label_9.setText(_translate("MainWindow", "Architecture: "))
        self.label_10.setText(_translate("MainWindow", "OS Type:"))
        self.label_11.setText(_translate("MainWindow", "Account ID:"))
        self.label_12.setText(_translate("MainWindow", "Connection Status:"))
        self.label_13.setText(_translate("MainWindow", "Authentication Status: "))
        self.label_14.setText(_translate("MainWindow", "Hostname:"))
        self.label_15.setText(_translate("MainWindow", "OS Version:"))
        self.label_16.setText(_translate("MainWindow", "Auth Key:"))
        self.label_17.setText(_translate("MainWindow", "Auth Salt: "))
        self.I_ip.setText(_translate("MainWindow", "<Not Fetched>"))
        self.E_ip.setText(_translate("MainWindow", "<Not Fetched>"))
        self.status.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Offline</span></p></body></html>"))
        self.processor.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#555500;\">&lt;Gathering Info&gt;</span></p></body></html>"))
        self.OS.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#555500;\">&lt;Gathering Info&gt;</span></p></body></html>"))
        self.OS_Type.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#555500;\">&lt;Gathering Info&gt;</span></p></body></html>"))
        self.Arch.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#555500;\">&lt;Gathering Info&gt;</span></p></body></html>"))
        self.Auth_stat.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">&lt;Not Authenticated&gt;</span></p></body></html>"))
        self.Hostname.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#555500;\">&lt;Gathering Info&gt;</span></p></body></html>"))
        self.Username.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">&lt;Not Logged In&gt;</span></p></body></html>"))
        self.aid.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">&lt;Not Logged In&gt;</span></p></body></html>"))
        self.Auth_key.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">&lt;Not Logged In&gt;</span></p></body></html>"))
        self.Auth_salt.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">&lt;Not Logged In&gt;</span></p></body></html>"))
        self.FetchIP.setText(_translate("MainWindow", "Fetch IP"))
        self.Login.setText(_translate("MainWindow", "Login!"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_4.setText(_translate("MainWindow", "Help"))
        self.pushButton_5.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

