# Generated by Django 3.1.1 on 2020-10-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_code', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200, null=True)),
                ('level_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.level')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree_code', models.IntegerField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=200, null=True)),
                ('level_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.level')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
