# Generated by Django 3.1.1 on 2020-10-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.IntegerField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='univDegree',
            fields=[
                ('univ_deg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('univ_deg_name', models.CharField(max_length=200, null=True)),
                ('university_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.university')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, null=True)),
                ('univ_deg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.univdegree')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('suggestion_code', models.IntegerField(primary_key=True, serialize=False)),
                ('topic1', models.CharField(max_length=200, null=True)),
                ('topic2', models.CharField(max_length=200, null=True)),
                ('topic3', models.CharField(max_length=200, null=True)),
                ('topic4', models.CharField(max_length=200, null=True)),
                ('topic5', models.CharField(max_length=200, null=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('university_id', models.ManyToManyField(to='students.University')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200, null=True)),
                ('univ_deg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.univdegree')),
            ],
        ),
    ]
