# Generated by Django 3.1.1 on 2020-10-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201020_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='degree_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.degree'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
