# Generated by Django 3.1.1 on 2020-10-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20201021_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='level_code',
            new_name='level',
        ),
    ]
