# Generated by Django 3.1.1 on 2020-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20201021_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='Website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='degree',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='topic1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='topic2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='topic3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='topic4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='topic5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
