# Generated by Django 3.1.1 on 2020-10-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20201021_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='topic4',
        ),
        migrations.RemoveField(
            model_name='university',
            name='topic5',
        ),
    ]
