# Generated by Django 3.1.1 on 2020-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20201021_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='topic1',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='university',
            name='topic2',
        ),
        migrations.RemoveField(
            model_name='university',
            name='topic3',
        ),
        migrations.AddField(
            model_name='university',
            name='level',
            field=models.CharField(choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(choices=[('High School', 'High School'), ('Under Graduate', 'Under Graduate')], max_length=200, null=True),
        ),
    ]
