# Generated by Django 3.1.1 on 2020-11-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20201021_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('MA', 'MA'), ('B.Sc', 'B.Sc'), ('BS', 'BS'), ('BA LLB', 'BA LLB'), ('B.Des.', 'B.Des.'), ('MBA', 'MBA'), ('MS', 'MS'), ('MBBS', 'MBBS'), ('B.Arch', 'B.Arch'), ('BE', 'BE'), ('M.Sc', 'M.Sc'), ('BA', 'BA'), ('DO', 'DO')], max_length=200, null=True),
        ),
    ]
