# Generated by Django 3.1.1 on 2020-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20201107_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='course',
            field=models.CharField(choices=[('CSE', 'CSE'), ('English', 'English'), ('EECS', 'EECS'), ('ASL', 'ASL'), ('GD', 'GD'), ('HRMS', 'HRMS'), ('AE', 'AE'), ('CSD', 'CSD'), ('MBBS', 'MBSS'), ('UPA', 'UPA'), ('ENI', 'ENI'), ('Physics', 'Physics'), ('AS', 'AS'), ('ECE', 'ECE'), ('HCI', 'HCI'), ('History', 'History'), ('Economics', 'Economics'), ('MECS', 'MECS'), ('IB', 'IB'), ('EEE', 'EEE'), ('Liberal Arts', 'Liberal Arts'), ('FD', 'FD'), ('ENT', 'ENT'), ('CE', 'CE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('China', 'China'), ('UK', 'UK')], max_length=200, null=True),
        ),
    ]
