# Generated by Django 3.1.1 on 2021-04-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20210428_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='University_Info',
            fields=[
                ('univ_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('univ_name', models.CharField(max_length=200, null=True)),
                ('research_paper', models.IntegerField(null=True)),
                ('placement_percent', models.IntegerField(null=True)),
                ('courses_available', models.IntegerField(null=True)),
                ('comp_visit', models.IntegerField(null=True)),
                ('avg_place_amt', models.IntegerField(null=True)),
                ('high_place_amt', models.IntegerField(null=True)),
                ('min_place_amt', models.IntegerField(null=True)),
                ('web', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
