# Generated by Django 3.1.1 on 2021-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_university_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_info',
            name='avg_place_amt',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='university_info',
            name='high_place_amt',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='university_info',
            name='min_place_amt',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
