# Generated by Django 3.1.1 on 2021-04-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20210429_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_info',
            name='placement_percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
