# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 568)
        MainWindow.setMinimumSize(QtCore.QSize(429, 568))
        MainWindow.setMaximumSize(QtCore.QSize(429, 568))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(350, 540, 75, 23))
        self.Exit.setObjectName("Exit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 540, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 540, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 411, 131))
        self.groupBox.setObjectName("groupBox")
        self.format = QtWidgets.QPushButton(self.groupBox)
        self.format.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.format.setObjectName("format")
        self.retrieve = QtWidgets.QPushButton(self.groupBox)
        self.retrieve.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.retrieve.setObjectName("retrieve")
        self.wipe = QtWidgets.QPushButton(self.groupBox)
        self.wipe.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.wipe.setObjectName("wipe")
        self.notify = QtWidgets.QPushButton(self.groupBox)
        self.notify.setGeometry(QtCore.QRect(310, 100, 91, 23))
        self.notify.setObjectName("notify")
        self.alarm = QtWidgets.QPushButton(self.groupBox)
        self.alarm.setGeometry(QtCore.QRect(120, 20, 91, 23))
        self.alarm.setObjectName("alarm")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(210, 10, 20, 121))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.sendanotification = QtWidgets.QLabel(self.groupBox)
        self.sendanotification.setGeometry(QtCore.QRect(230, 6, 101, 16))
        self.sendanotification.setObjectName("sendanotification")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(230, 30, 47, 13))
        self.label.setObjectName("label")
        self.messagecontent = QtWidgets.QTextEdit(self.groupBox)
        self.messagecontent.setGeometry(QtCore.QRect(283, 30, 121, 61))
        self.messagecontent.setObjectName("messagecontent")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 401, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.screenshot = QtWidgets.QPushButton(self.groupBox_2)
        self.screenshot.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.screenshot.setObjectName("screenshot")
        self.loc = QtWidgets.QPushButton(self.groupBox_2)
        self.loc.setGeometry(QtCore.QRect(10, 60, 91, 23))
        self.loc.setObjectName("loc")
        self.webcam = QtWidgets.QPushButton(self.groupBox_2)
        self.webcam.setGeometry(QtCore.QRect(10, 100, 91, 23))
        self.webcam.setObjectName("webcam")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 480, 401, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.shell = QtWidgets.QPushButton(self.groupBox_3)
        self.shell.setGeometry(QtCore.QRect(40, 20, 91, 23))
        self.shell.setObjectName("shell")
        self.usage_cpu = QtWidgets.QPushButton(self.groupBox_3)
        self.usage_cpu.setGeometry(QtCore.QRect(170, 20, 91, 23))
        self.usage_cpu.setObjectName("usage_cpu")
        self.activity = QtWidgets.QPushButton(self.groupBox_3)
        self.activity.setGeometry(QtCore.QRect(290, 20, 91, 23))
        self.activity.setObjectName("activity")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 310, 401, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(401, 161))
        self.textEdit.setMaximumSize(QtCore.QSize(401, 161))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CyberHawk - Master"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_3.setText(_translate("MainWindow", "About"))
        self.pushButton_4.setText(_translate("MainWindow", "Help"))
        self.groupBox.setTitle(_translate("MainWindow", "Remote Administration Tools:"))
        self.format.setText(_translate("MainWindow", "Format Drive"))
        self.retrieve.setText(_translate("MainWindow", "Retrieve Files"))
        self.wipe.setText(_translate("MainWindow", "Wipe Device"))
        self.notify.setText(_translate("MainWindow", "Notify User"))
        self.alarm.setText(_translate("MainWindow", "Alarm"))
        self.sendanotification.setText(_translate("MainWindow", "Send a Notification:"))
        self.label.setText(_translate("MainWindow", "Message:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Know the Intruder"))
        self.screenshot.setText(_translate("MainWindow", "Screenshot"))
        self.loc.setText(_translate("MainWindow", "Geolocation"))
        self.webcam.setText(_translate("MainWindow", "Webcam Stream"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Advanced Options (Experimental)"))
        self.shell.setText(_translate("MainWindow", "Open Shell"))
        self.usage_cpu.setText(_translate("MainWindow", "Retrieve Usage"))
        self.activity.setText(_translate("MainWindow", "Activity Tracker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

