website_entry = Entry(width=35)
# website_entry.grid(row=1,column=1,columnspan=3)
# email_entry = Entry(width=35)
# email_entry.grid(row=2,column=1,columnspan=3)
# password_entry = Entry(width=21)
# password_entry.grid(row=3,column=1)
