# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from cipher import decrypt

class TestDecrypt(unittest.TestCase):

    def test_Decrypt_10c2ea9e76(self):
        # Test Case 1: Testing with normal string and decryption number
        message = "ifmmp"
        decryptNum = 1
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "hello")

        # Test Case 2: Testing with string having numbers and decryption number
        message = "jg 2"
        decryptNum = 1
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "if 1")

        # Test Case 3: Testing with string having special characters and decryption number
        message = "kvohtp!"
        decryptNum = 2
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "iulgn!")

        # Test Case 4: Testing with string having upper case letters and decryption number
        message = "JG 2"
        decryptNum = 1
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "IF 1")

        # Test Case 5: Testing with empty string and decryption number
        message = ""
        decryptNum = 1
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "")

        # Test Case 6: Testing with decryption number as zero
        message = "hello"
        decryptNum = 0
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "hello")

        # Test Case 7: Testing with decryption number greater than 26
        message = "ifmmp"
        decryptNum = 27
        result = decrypt(message, decryptNum)
        self.assertEqual(result, "hello")

if __name__ == '__main__':
    unittest.main()
