# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from cipher import isCharacter

class TestIsCharacter(unittest.TestCase):
    
    def test_IsCharacter_5d8094df9c(self):
        # Test with a valid character
        self.assertTrue(isCharacter('a'), "The function failed to identify a valid character.")
        
        # Test with an invalid character
        self.assertFalse(isCharacter('1'), "The function incorrectly identified a number as a character.")
        
        # Test with a special character
        self.assertFalse(isCharacter('@'), "The function incorrectly identified a special character as a character.")
        
        # Test with an empty string
        self.assertFalse(isCharacter(''), "The function incorrectly identified an empty string as a character.")
        
        # Test with a string of multiple characters
        self.assertFalse(isCharacter('abc'), "The function incorrectly identified a string of multiple characters as a single character.")
        
        # Test with a capital letter
        self.assertTrue(isCharacter('A'), "The function failed to identify a capital letter as a valid character.")
        
if __name__ == '__main__':
    unittest.main()
