# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from cipher import isSpecialChar

class TestSpecialChar(unittest.TestCase):

    def test_IsSpecialChar_8fe3ae6f12(self):
        # Test case 1: Check with special character
        element = '@'
        result = isSpecialChar(element)
        self.assertEqual(result, True, "Failed: Expected True, Got False")

        # Test case 2: Check with non-special character
        element = 'A'
        result = isSpecialChar(element)
        self.assertEqual(result, False, "Failed: Expected False, Got True")

        # Test case 3: Check with special character as string
        element = '#$%'
        result = isSpecialChar(element)
        self.assertEqual(result, True, "Failed: Expected True, Got False")

        # Test case 4: Check with number
        element = '123'
        result = isSpecialChar(element)
        self.assertEqual(result, False, "Failed: Expected False, Got True")

if __name__ == '__main__':
    unittest.main()
