# Test generated by RoostGPT for test awesome-python-ceaser-cipher using AI Type Open AI and AI Model gpt-4

import unittest
from cipher import isNumber

class TestIsNumber(unittest.TestCase):

    def test_IsNumber_ed9ccec17b(self):
        # Test case 1: Check for a positive integer
        self.assertTrue(isNumber(5), "Failed: 5 is a valid number but function returned False")

        # Test case 2: Check for a negative integer
        self.assertFalse(isNumber(-5), "Failed: -5 is not a valid number but function returned True")

        # Test case 3: Check for a string that can be converted to an integer
        self.assertTrue(isNumber('7'), "Failed: '7' is a valid number but function returned False")

        # Test case 4: Check for a string that cannot be converted to an integer
        self.assertFalse(isNumber('abc'), "Failed: 'abc' is not a valid number but function returned True")

        # Test case 5: Check for a float
        self.assertFalse(isNumber(4.5), "Failed: 4.5 is not a valid number but function returned True")

if __name__ == '__main__':
    unittest.main()
